### ISSUE TITLE
on('logout')

### ISSUE THREAD

**Issue by LucatonyRaudales** [tazzix/tazz_socket#1]
when i disconnect from server and i listen in flutter on('logout') event into client service generate next error: 

D/ViewRootImpl(22493): ViewPostImeInputStage processPointer 1
D/SocketIO  (22493): registering to logout topic
E/AndroidRuntime(22493): FATAL EXCEPTION: EventThread
E/AndroidRuntime(22493): Process: com.example.eco_movil, PID: 22493
E/AndroidRuntime(22493): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(22493):        at com.tazzix.tazzsocket.TazzSocket$3.call(TazzSocket.java:138)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:317)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:280)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:101)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:382)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.access$1200(Manager.java:21)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:356)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:374)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.access$1000(Manager.java:21)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:347)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:497)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:30)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:300)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:124)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:116)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.transports.WebSocket.access$300(WebSocket.java:26)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:102)
E/AndroidRuntime(22493):        at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
E/AndroidRuntime(22493):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime(22493):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime(22493):        at java.lang.Thread.run(Thread.java:818)
D/libEGL  (22493): eglTerminate EGLDisplay = 0xbe9dd94c
D/ViewRootImpl(22493): #3 mView = null
E/ActivityThread(22493): Activity com.example.eco_movil.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@881d6e8 that was originally bound here
E/ActivityThread(22493): android.app.ServiceConnectionLeaked: Activity com.example.eco_movil.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@881d6e8 that was originally bound here
E/ActivityThread(22493):        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
E/ActivityThread(22493):        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
E/ActivityThread(22493):        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1416)
E/ActivityThread(22493):        at android.app.ContextImpl.bindService(ContextImpl.java:1399)
E/ActivityThread(22493):        at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
E/ActivityThread(22493):        at com.almoullim.background_location.BackgroundLocationPlugin.onMethodCall(BackgroundLocationPlugin.kt:79)
E/ActivityThread(22493):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/ActivityThread(22493):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/ActivityThread(22493):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/ActivityThread(22493):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(22493):        at android.os.MessageQueue.next(MessageQueue.java:323)
E/ActivityThread(22493):        at android.os.Looper.loop(Looper.java:143)
E/ActivityThread(22493):        at android.app.ActivityThread.main(ActivityThread.java:7224)
E/ActivityThread(22493):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(22493):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/ActivityThread(22493):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

I/Process (22493): Sending signal. PID: 22493 SIG: 9
Lost connection to device.
MacBook-de-Tony:Eco-mobile tonyraudales$

**Comment by LucatonyRaudales** [comment]
D/ViewRootImpl(22493): ViewPostImeInputStage processPointer 1
D/SocketIO  (22493): registering to logout topic
E/AndroidRuntime(22493): FATAL EXCEPTION: EventThread
E/AndroidRuntime(22493): Process: com.example.eco_movil, PID: 22493
E/AndroidRuntime(22493): java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
E/AndroidRuntime(22493):        at com.tazzix.tazzsocket.TazzSocket$3.call(TazzSocket.java:138)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:317)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:280)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:101)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:382)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.access$1200(Manager.java:21)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:356)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:374)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager.access$1000(Manager.java:21)
E/AndroidRuntime(22493):        at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:347)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:497)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:30)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:300)
E/AndroidRuntime(22493):        at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:124)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.Transport.onData(Transport.java:116)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.transports.WebSocket.access$300(WebSocket.java:26)
E/AndroidRuntime(22493):        at com.github.nkzawa.engineio.client.transports.WebSocket$1$3.run(WebSocket.java:102)
E/AndroidRuntime(22493):        at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
E/AndroidRuntime(22493):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime(22493):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime(22493):        at java.lang.Thread.run(Thread.java:818)
D/libEGL  (22493): eglTerminate EGLDisplay = 0xbe9dd94c
D/ViewRootImpl(22493): #3 mView = null
E/ActivityThread(22493): Activity com.example.eco_movil.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@881d6e8 that was originally bound here
E/ActivityThread(22493): android.app.ServiceConnectionLeaked: Activity com.example.eco_movil.MainActivity has leaked ServiceConnection com.almoullim.background_location.BackgroundLocationPlugin$mServiceConnection$1@881d6e8 that was originally bound here
E/ActivityThread(22493):        at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1204)
E/ActivityThread(22493):        at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1098)
E/ActivityThread(22493):        at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1416)
E/ActivityThread(22493):        at android.app.ContextImpl.bindService(ContextImpl.java:1399)
E/ActivityThread(22493):        at android.content.ContextWrapper.bindService(ContextWrapper.java:632)
E/ActivityThread(22493):        at com.almoullim.background_location.BackgroundLocationPlugin.onMethodCall(BackgroundLocationPlugin.kt:79)
E/ActivityThread(22493):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/ActivityThread(22493):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/ActivityThread(22493):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/ActivityThread(22493):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/ActivityThread(22493):        at android.os.MessageQueue.next(MessageQueue.java:323)
E/ActivityThread(22493):        at android.os.Looper.loop(Looper.java:143)
E/ActivityThread(22493):        at android.app.ActivityThread.main(ActivityThread.java:7224)
E/ActivityThread(22493):        at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(22493):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
E/ActivityThread(22493):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

I/Process (22493): Sending signal. PID: 22493 SIG: 9
Lost connection to device.
MacBook-de-Tony:Eco-mobile tonyraudales$
